### ISSUE TITLE
Twilight Forest crops through Mystical Agriculture can't be used with Agricraft crop sticks

### ISSUE THREAD

**Issue by merdink** [sibomots/FooFarm#21]
For example, Ironwood/Knightmetal/Fiery Ingot/Steeleaf can't be planted in Agricraft's crop sticks
The solution seems to be to add JSON files to the Mystical Agriculture folder in the Agricraft config JSON folder.
[https://agridocs.readthedocs.io/en/latest/agri_plant/](url)

Should we add the JSON files, or would that not be in the spirit of the pack? Not sure how we would vote or decide on this.

**Comment by sibomots** [comment]
I'm unclear if this a defect in the behavior of the mod, or a necessary patch to make the mods work together.

if they are meant to work together (ie., Ingot X *can* be planted in  Agricraft crop sticks) then I think the config should be changed to allow it.

What's the downside if we allow it?

If there is no down-side, what's the up-side to allow it?

Since we don't have quite enough users to really have a good sampling for "voting" on this,  I'll defer to those with better domain knowledge
.

**Comment by merdink** [comment]
Since we can already grow the diamond plants in the Agricraft crop sticks, we might as well just add the Twilight Forest stuff also.
