### ISSUE TITLE
Hunger Overhaul is affecting trade with Villagers

### ISSUE THREAD

**Issue by merdink** [sibomots/FooFarm#8]
I was going to trade 40 rotten Flesh to with a Villager for an emerald. Until I remembered that because of Hunger Overhaul's modification of the food stacks, i couldn't give the Villager the 40 rotten flesh for an emerald. Not sure how to fix it since I don't want to cripple Hunger Overhaul to fix it.

**Comment by Drakonas** [comment]
Personally, I think Hunger Overhaul is a bit much when being the only food mod. Steak is only 1 hunger... there is no consistency. Bread is 1 & 1/2 Hunger. Granted, the main issue is Hunger Overhaul works best when there are food mods with much more advanced recipes, like Pam's Harvestcraft. But the fact that Hunger Overhaul modified the vanilla recipes' traits is probably the main issue for this.

If alone, I can understand this pack wanting to benefit from Hunger Overhaul, since the pack is based on difficulty. But without another food mod, it just makes everything kind of bland. Instead of opting to spend time to automate something a bit more in-depth like a cow farm, you might as well just plant one of the first crops you collect: Barley, for a practically infinite food source without any effort and any time taken.

What was thought to be difficulty just ends up being easy but frustrating.

I'd advise one of two options: remove Hunger Overhaul, or keep it and add Pam's Harvestcraft (as well as configure Hunger Overhaul to make sure it's treating the different tiers properly, if that's required)

I mean, it states it on the Hunger Overhaul page pretty clearly:
        *** HarvestCraft is highly recommended to get the full experience ***

**Comment by sibomots** [comment]
The resolution is the upgrade to 1.2.

Added:

AgriCraft-2.12.0-1.12.0-a6.jar
tinkersjei-1.2.jar
jei_1.12.2-4.16.1.301.jar
SpiceOfLife-mc1.12-1.3.12.jar
StorageDrawers-1.12.2-5.4.2.jar
Animus-1.12-2.1.7.jar
Pam's BrewCraft 1.12.2-1.0.2.jar
Pam's HarvestCraft 1.12.2zg.jar
Pam's Simple Recipes 1.12.2c.jar
Pam's Get all the Seeds! 1.12a.jar
Chameleon-1.12-4.1.3.jar
CTM-MC1.12.2-1.0.2.31.jar
Botania r1.10-363.jar
bloodagricraft-1.0.0.jar
pamscookables-1.1.jar
CookingForBlockheads_1.12.2-6.5.0.jar
infinitylib-1.12.0.jar
